# Generated by Django 4.2.2 on 2023-06-19 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0003_account_balance_account_user_order_client_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='enterprise.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.00, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
