# Generated by Django 4.2.2 on 2023-06-19 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0007_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 19, 11, 56, 44, 39462, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
