# Generated by Django 4.2.2 on 2023-06-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0008_alter_transaction_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
