# Generated by Django 4.2.2 on 2023-06-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0013_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
