# Generated by Django 4.2.2 on 2023-06-26 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0014_order_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='order_code',
        ),
    ]
