# Generated by Django 4.2.2 on 2023-06-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0016_monthlyinstallment_order_paid_order_paid_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('pc_code', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='enterprise.productcategory'),
        ),
    ]
