# Generated by Django 4.2.2 on 2023-06-27 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0017_productcategory_remove_product_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='LoanPayment',
        ),
    ]
