# Generated by Django 4.2.2 on 2023-06-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0022_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='e_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
