# Generated by Django 4.2.2 on 2023-06-28 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0024_alter_expense_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='user',
            new_name='staff',
        ),
    ]
