# Generated by Django 4.2.2 on 2023-06-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0025_rename_user_expense_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'verbose_name_plural': 'ExpenseCategories'},
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='ec_code',
            field=models.CharField(default='71594858-2f68-4ca7-917b-7e2498b7b073', max_length=50),
        ),
    ]
