# Generated by Django 4.2.2 on 2023-07-01 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0027_alter_order_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='ec_code',
            field=models.CharField(default='69f1c440-9f77-4154-88d8-cc30debee69f', max_length=50),
        ),
    ]
