# Generated by Django 4.2.2 on 2023-07-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0028_order_staff_alter_expensecategory_ec_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('total_expenses', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=8)),
                ('profit_loss', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='ec_code',
            field=models.CharField(default='04db657d-6170-4205-b8bc-3d095aceb01e', max_length=50),
        ),
    ]
