# Generated by Django 4.2.2 on 2023-07-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0029_monthlydata_alter_expensecategory_ec_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='ec_code',
            field=models.CharField(default='f38dead4-5ce6-49e6-a924-64709e4b4d88', max_length=50),
        ),
        migrations.AlterField(
            model_name='monthlydata',
            name='profit_loss',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='monthlydata',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='monthlydata',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
