# Generated by Django 4.2.2 on 2023-07-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0030_alter_expensecategory_ec_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='ec_code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
