# Generated by Django 4.2.2 on 2023-07-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0033_product_buy_price_product_date_alter_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlydata',
            name='profit_loss',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='monthlydata',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='monthlydata',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
